
package br.edu.ifgoiano.siirioverde.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SiiRioVerdeWs", targetNamespace = "http://ws.siirioverde.ifgoiano.edu.br/", wsdlLocation = "http://10.2.16.86:8080/SistemaDeControleDePesquisa/SiiRioVerdeWs?WSDL")
public class SiiRioVerdeWs_Service
    extends Service
{

    private final static URL SIIRIOVERDEWS_WSDL_LOCATION;
    private final static WebServiceException SIIRIOVERDEWS_EXCEPTION;
    private final static QName SIIRIOVERDEWS_QNAME = new QName("http://ws.siirioverde.ifgoiano.edu.br/", "SiiRioVerdeWs");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://10.2.16.86:8080/SistemaDeControleDePesquisa/SiiRioVerdeWs?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SIIRIOVERDEWS_WSDL_LOCATION = url;
        SIIRIOVERDEWS_EXCEPTION = e;
    }

    public SiiRioVerdeWs_Service() {
        super(__getWsdlLocation(), SIIRIOVERDEWS_QNAME);
    }

    public SiiRioVerdeWs_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), SIIRIOVERDEWS_QNAME, features);
    }

    public SiiRioVerdeWs_Service(URL wsdlLocation) {
        super(wsdlLocation, SIIRIOVERDEWS_QNAME);
    }

    public SiiRioVerdeWs_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SIIRIOVERDEWS_QNAME, features);
    }

    public SiiRioVerdeWs_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SiiRioVerdeWs_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SiiRioVerdeWs
     */
    @WebEndpoint(name = "SiiRioVerdeWsPort")
    public SiiRioVerdeWs getSiiRioVerdeWsPort() {
        return super.getPort(new QName("http://ws.siirioverde.ifgoiano.edu.br/", "SiiRioVerdeWsPort"), SiiRioVerdeWs.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SiiRioVerdeWs
     */
    @WebEndpoint(name = "SiiRioVerdeWsPort")
    public SiiRioVerdeWs getSiiRioVerdeWsPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.siirioverde.ifgoiano.edu.br/", "SiiRioVerdeWsPort"), SiiRioVerdeWs.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SIIRIOVERDEWS_EXCEPTION!= null) {
            throw SIIRIOVERDEWS_EXCEPTION;
        }
        return SIIRIOVERDEWS_WSDL_LOCATION;
    }

}
